### ISSUE TITLE
win can't install

### ISSUE THREAD

**Issue by Environmental-lion** [thiagoralves/OpenPLC_v3#255]
![0641163fb36b4c2afcae59c7467ebcf](https://github.com/user-attachments/assets/9b5cc6d5-381c-4c52-ab2a-81c6b047548e)

**Comment by thiagoralves** [comment]
Sorry, there seems to be a glitch on the code rendering for the website docs. The command must have two dashes for the "noconfirm" option (should be --noconfirm instead of -noconfirm). Even though the text contain two dashes, the docs page is rendering only one. I've changed the format of the display box to show the actual command that needs to be typed in. Now the instructions are correct. Please try again.

Also, did you try the automatic installer from the docs page? Didn't it work for you?

**Comment by Environmental-lion** [comment]
The automatic installer will crash.I want to take a screenshot for you.But it crash very fast.

**Comment by Environmental-lion** [comment]
![26ff015f60115006f413b4b68e78521](https://github.com/user-attachments/assets/accd30c3-bdf2-4fd4-95f1-a42f16233214)
![5b6f7f84b127a72a18d26ccfa8d0547](https://github.com/user-attachments/assets/ece9d059-0197-4123-b6b6-ad6cdd57481a)
It unsuccessful.

**Comment by thiagoralves** [comment]
You must type one command at a time. Only the first command was processed.

**Comment by Environmental-lion** [comment]
![image](https://github.com/user-attachments/assets/468dc2b9-4a81-4a4a-aab9-3174ece5551b)
I've tried so many times.

**Comment by thiagoralves** [comment]
You must be on a filtered internet which is causing the SSL certificate to fail. You have two options: 
1. move to an unfiltered internet where you can download stuff
2. try to download the OpenPLC repository straight from GitHub and then extract it inside your MSYS2 folder.
