### ISSUE TITLE
database + schema

### ISSUE THREAD

**Issue by pedromorgan** [thiagoralves/OpenPLC_v3#5]
So I realise that the 
- sqlite db is in version control 
-  and cannot see any schema creation scripts ( do they exists )

Guess the db needs to be created on setup and places in users home dir etc

**Comment by pedromorgan** [comment]
Also suggest using dict for row's returned instead of tuple, as its less confusing, imho
ie `row['foo']` instead of `row[4]`
https://stackoverflow.com/questions/3300464/how-can-i-get-dict-from-sqlite-query

**Comment by pedromorgan** [comment]
Ok so after so thought, and thinking out loud,

do we really needs sqlite ??

can't this stuff be stored in a "workspace with folders" in json, yaml, toml etc ??
indeed a per project folder etc..

Whats limiting about sqlite ??
maintaining future different db's different schema versions etc...
eg query crash cos table not htere...
Whereas if it was in nosql = files (in git even)
then the whole lot can be handled better..

**Comment by pedromorgan** [comment]
Also check http://json-schema.org/

Is kinda maube an idea..
or whatever ptorocl files can grap from internet.

**Comment by thiagoralves** [comment]
Initially I didn't want to use a database. I was going to store everything on CSV files (I know, hardware guys love CSV). But then I though a db would make my life a lot easier, so I went with the simplest one available. However, JSON might be more interesting. The only problem is to translate the whole project to use JSON instead of db.

**Comment by thiagoralves** [comment]
I'll close this for now until there is more progress on the subject...
